# Generated by Django 5.0.6 on 2024-05-23 16:12

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chat_members_remove_messages_rasm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='rasm',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='members',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='reply',
        ),
        migrations.AddField(
            model_name='chat',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messages',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messages',
            name='sms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
