# Generated by Django 5.0.6 on 2024-06-07 06:37

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='rasm'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
